---
default: true

MD004:
  style: dash

MD013:
  line_length: 120
  heading_line_length: 120
  code_blocks: false

MD024: false

MD033:
  allowed_elements:
    - br
    - kdb
    - pre
    - script

MD034: false

MD049:
  style: asterisk
